# Docker Compose file for scalable PX4-AirSim integration
# Uses proper port offsets for multiple containers

services:
  px4:
    build: 
      context: .
      dockerfile: Dockerfile
    # Don't set container_name to allow Docker Compose scaling
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
    # No fixed ports - we'll use Docker's automatic assignment
    networks:
      - airsim-network
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: >
      bash -c "
      # Extract instance number from container name
      CONTAINER_NAME=$$(hostname);
      echo 'Container name: '$$CONTAINER_NAME;
      
      # Extract number from the end of container name (e.g., px4_airsim_docker-px4-1 -> 1)
      INSTANCE_NUM=$$(echo $$CONTAINER_NAME | sed 's/.*-//');
      
      # If no number found, default to 1
      if ! echo $$INSTANCE_NUM | grep -q '^[0-9]*$$'; then
        INSTANCE_NUM=1;
      fi;
      
      echo 'Detected instance number: '$$INSTANCE_NUM;
      
      # Calculate unique ports for this instance
      TCP_PORT=$$((4560 + INSTANCE_NUM));
      MAVLINK_LOCAL=$$((14540 + INSTANCE_NUM));
      MAVLINK_REMOTE=$$((14580 + INSTANCE_NUM));
      QGC_PORT=$$((14549 + INSTANCE_NUM));
      
      echo '🚁 Starting PX4 SITL instance '$$INSTANCE_NUM;
      echo '   TCP Port (AirSim): '$$TCP_PORT;
      echo '   MAVLink Local: '$$MAVLINK_LOCAL;
      echo '   MAVLink Remote: '$$MAVLINK_REMOTE;
      echo '   QGroundControl: '$$QGC_PORT;
      
      # Set environment variables for the PX4 script
      export PX4_INSTANCE=$$INSTANCE_NUM;
      export PX4_TCP_PORT=$$TCP_PORT;
      export PX4_MAVLINK_LOCAL=$$MAVLINK_LOCAL;
      export PX4_MAVLINK_REMOTE=$$MAVLINK_REMOTE;
      export PX4_QGC_PORT=$$QGC_PORT;
      
      # Start PX4 with the calculated instance number
      /Scripts/run_airsim_sitl_final.sh $$INSTANCE_NUM
      "

# Explicit service definitions for better control (alternative approach)
  px4-1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: px4-drone-1
    hostname: px4-drone-1
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      - PX4_INSTANCE=1
    ports:
      # - "4561:4561/tcp"     # AirSim TCP
      - "14541:14541/udp"   # MAVLink Local
      - "14581:14581/udp"   # MAVLink Remote
      - "14550:14550/udp"   # QGroundControl
    networks:
      airsim-network:
        ipv4_address: 172.25.0.10
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    command: ["/Scripts/run_airsim_sitl_final.sh", "1"]
    profiles:
      - explicit

  px4-2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: px4-drone-2
    hostname: px4-drone-2
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      - PX4_INSTANCE=2
    ports:
      # - "4562:4562/tcp"     # AirSim TCP
      - "14542:14542/udp"   # MAVLink Local
      - "14582:14582/udp"   # MAVLink Remote
      - "14551:14551/udp"   # QGroundControl
    networks:
      airsim-network:
        ipv4_address: 172.25.0.11
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    command: ["/Scripts/run_airsim_sitl_final.sh", "2"]
    profiles:
      - explicit

  px4-3:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: px4-drone-3
    hostname: px4-drone-3
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      - PX4_INSTANCE=3
    ports:
      # - "4563:4563/tcp"     # AirSim TCP
      - "14543:14543/udp"   # MAVLink Local
      - "14583:14583/udp"   # MAVLink Remote
      - "14552:14552/udp"   # QGroundControl
    networks:
      airsim-network:
        ipv4_address: 172.25.0.12
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    command: ["/Scripts/run_airsim_sitl_final.sh", "3"]
    profiles:
      - explicit

  px4-4:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: px4-drone-4
    hostname: px4-drone-4
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      - PX4_INSTANCE=4
    ports:
      # - "4564:4564/tcp"     # AirSim TCP
      - "14544:14544/udp"   # MAVLink Local
      - "14584:14584/udp"   # MAVLink Remote
      - "14553:14553/udp"   # QGroundControl
    networks:
      airsim-network:
        ipv4_address: 172.25.0.13
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    command: ["/Scripts/run_airsim_sitl_final.sh", "4"]
    profiles:
      - explicit

  px4-5:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: px4-drone-5
    hostname: px4-drone-5
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      - PX4_INSTANCE=5
    ports:
      # - "4565:4565/tcp"     # AirSim TCP
      - "14545:14545/udp"   # MAVLink Local
      - "14585:14585/udp"   # MAVLink Remote
      - "14554:14554/udp"   # QGroundControl
    networks:
      airsim-network:
        ipv4_address: 172.25.0.14
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    command: ["/Scripts/run_airsim_sitl_final.sh", "5"]
    profiles:
      - explicit

# Networks
networks:
  airsim-network:
    name: airsim-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

# Volumes
volumes:
  px4-shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared_data 