services:
  # Base service template - not actually run (using profiles to prevent creation)
  px4-base: &px4-base
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    networks:
      - airsim-network
    volumes:
      - px4-data:/px4_data
    restart: unless-stopped
    profiles:
      - never  # This ensures the base template is never started

  # Single Drone Configuration
  px4-single:
    <<: *px4-base
    container_name: px4-single
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_INSTANCE=1
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    ports:
      - "4561:4561/tcp"    # AirSim connection for single drone
      - "14550:14550/udp"  # QGC for single drone
      - "14541:14541/udp"  # MAVLink control local
      - "14581:14581/udp"  # MAVLink control remote
    networks:
      airsim-network:
        ipv4_address: 172.30.0.10
    profiles:
      - single

  # Multi-Drone Configuration - Drone 1
  px4-drone-1:
    <<: *px4-base
    container_name: px4-drone-1
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_INSTANCE=1
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    ports:
      - "4561:4561/tcp"    # AirSim connection for drone 1
      - "14550:14550/udp"  # QGC for drone 1
      - "14541:14541/udp"  # MAVLink control local
      - "14581:14581/udp"  # MAVLink control remote
    networks:
      airsim-network:
        ipv4_address: 172.30.0.10
    profiles:
      - multi
      - drone-2
      - drone-3
      - drone-4
      - drone-5

  # Multi-Drone Configuration - Drone 2
  px4-drone-2:
    <<: *px4-base
    container_name: px4-drone-2
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_INSTANCE=2
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    ports:
      - "4562:4562/tcp"    # AirSim connection for drone 2
      - "14551:14550/udp"  # QGC for drone 2 (unique host port)
      - "14542:14542/udp"  # MAVLink control local
      - "14582:14582/udp"  # MAVLink control remote
    networks:
      airsim-network:
        ipv4_address: 172.30.0.11
    profiles:
      - multi
      - drone-2
      - drone-3
      - drone-4
      - drone-5

  # Multi-Drone Configuration - Drone 3
  px4-drone-3:
    <<: *px4-base
    container_name: px4-drone-3
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_INSTANCE=3
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    ports:
      - "4563:4563/tcp"    # AirSim connection for drone 3
      - "14552:14550/udp"  # QGC for drone 3 (unique host port)
      - "14543:14543/udp"  # MAVLink control local
      - "14583:14583/udp"  # MAVLink control remote
    networks:
      airsim-network:
        ipv4_address: 172.30.0.12
    profiles:
      - multi
      - drone-3
      - drone-4
      - drone-5

  # Multi-Drone Configuration - Drone 4
  px4-drone-4:
    <<: *px4-base
    container_name: px4-drone-4
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_INSTANCE=4
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    ports:
      - "4564:4564/tcp"    # AirSim connection for drone 4
      - "14553:14550/udp"  # QGC for drone 4 (unique host port)
      - "14544:14544/udp"  # MAVLink control local
      - "14584:14584/udp"  # MAVLink control remote
    networks:
      airsim-network:
        ipv4_address: 172.30.0.13
    profiles:
      - multi
      - drone-4
      - drone-5

  # Multi-Drone Configuration - Drone 5
  px4-drone-5:
    <<: *px4-base
    container_name: px4-drone-5
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_INSTANCE=5
      - PX4_SIM_HOSTNAME=127.0.0.1
      - PX4_SIM_MODEL=none_iris
      - PX4_SIMULATOR=none
    ports:
      - "4565:4565/tcp"    # AirSim connection for drone 5
      - "14554:14550/udp"  # QGC for drone 5 (unique host port)
      - "14545:14545/udp"  # MAVLink control local
      - "14585:14585/udp"  # MAVLink control remote
    networks:
      airsim-network:
        ipv4_address: 172.30.0.14
    profiles:
      - multi
      - drone-5

# Shared network for all AirSim components
networks:
  airsim-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

# Shared volumes
volumes:
  px4-data:
    driver: local 