# Docker Compose file for scalable PX4-AirSim integration
# Uses range-based port publishing and Docker Compose scaling

services:
  px4:
    build: 
      context: .
      dockerfile: Dockerfile
    # Remove container_name to let Docker Compose auto-generate scaled names
    # hostname: px4-drone
    environment:
      # Base environment - each scaled instance will increment ports automatically
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      # These will be overridden by scaling
      - PX4_INSTANCE=1
      - PX4_UDP_PORT=4561
      - PX4_MAVLINK_LOCAL_PORT=14541
      - PX4_MAVLINK_REMOTE_PORT=14581
      - PX4_QGC_PORT=14550
    ports:
      # Range-based port publishing for up to 10 drones (4561-4570)
      # - "4561-4570:4561-4570/tcp"  # AirSim TCP connections
      # MAVLink UDP ports for control (14541-14550 local, 14581-14590 remote)
      - "14541-14550:14541-14550/udp"  # MAVLink control local
      - "14581-14590:14581-14590/udp"  # MAVLink control remote
      # QGroundControl ports (14550-14559)
      - "14550-14559:14550-14559/udp"  # QGroundControl connections
      # PX4 SITL UDP ports (18570-18579)
      - "18570-18579:18570-18579/udp"  # PX4 SITL internal
    networks:
      - airsim-network
    volumes:
      - px4-shared-data:/px4_data
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: >
      bash -c "
      echo '🚁 Starting PX4 SITL instance 1';
      echo '   TCP Port (AirSim): 4561';
      echo '   MAVLink Local: 14541';
      echo '   MAVLink Remote: 14581';
      echo '   QGroundControl: 14550';
      
      export PX4_INSTANCE=1;
      /Scripts/run_airsim_sitl_final.sh 1
      "

  # ROS2 AirSim Wrapper (optional)
  airsim-ros2:
    image: airsim-ros2-wrapper:latest
    container_name: airsim-ros2
    hostname: airsim-ros2
    environment:
      - ROS_DOMAIN_ID=0
      - AIRSIM_HOST_IP=host.docker.internal
      - AIRSIM_HOST_PORT=41451
      - LAUNCH_RVIZ=false
      - DISPLAY=${DISPLAY:-}
    networks:
      airsim-network:
        ipv4_address: 172.25.0.20
    depends_on:
      - px4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    restart: unless-stopped
    profiles:
      - ros2

  # Debug container for troubleshooting
  px4-debug:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: px4-debug
    hostname: px4-debug
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
      - PX4_SYS_AUTOSTART=10016
      - PX4_SIM_HOSTNAME=host.docker.internal
      - PX4_SIM_MODEL=iris
      - PX4_INSTANCE=999
    command: ["/bin/bash"]
    networks:
      airsim-network:
        ipv4_address: 172.25.0.99
    tty: true
    stdin_open: true
    profiles:
      - debug

# Networks
networks:
  airsim-network:
    name: airsim-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

# Volumes
volumes:
  px4-shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared_data 