# Ultra-Swarm Docker Compose Configuration with Bridge Network
# This version uses Docker bridge networking instead of host networking
# for better compatibility with Docker Desktop on Windows/WSL2

networks:
  px4_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

x-px4-common: &px4-common
  build:
    context: .
    dockerfile: Dockerfile
  environment: &px4-env
    PX4_SIM_HOSTNAME: 172.28.240.1 #host.docker.internal
    PX4_SIM_MODEL: iris
    DELAYED_START: true
  networks:
    - px4_network
  volumes:
    - px4-shared-data:/px4_data
    # Mount PX4Scripts directory so containers can access run_airsim_sitl.sh
    - ../../PX4Scripts:/host_px4scripts:ro
  restart: unless-stopped
  tty: true
  stdin_open: true
  # Keep container running without starting PX4 immediately
  command: >
    bash -c "
      # Create Scripts directory if it doesn't exist
      mkdir -p /px4_workspace/PX4-Autopilot/Scripts
      
      # Copy the script on startup for easy access
      if [ -f '/host_px4scripts/run_airsim_sitl.sh' ]; then
        echo '📋 Copying run_airsim_sitl.sh from host...'
        cp /host_px4scripts/run_airsim_sitl.sh /px4_workspace/PX4-Autopilot/Scripts/
        chmod +x /px4_workspace/PX4-Autopilot/Scripts/run_airsim_sitl.sh
      else
        echo '⚠️  run_airsim_sitl.sh not found in mounted volume'
        echo 'Expected: /host_px4scripts/run_airsim_sitl.sh'
      fi
      
      echo '🔄 Container started in delayed mode (bridge network)'
      echo '   Instance: $$PX4_INSTANCE ready'
      echo '   Network: Bridge (host.docker.internal)'
      echo '   To start PX4 SITL, run inside container:'
      echo '   cd /px4_workspace/PX4-Autopilot && ./Scripts/run_airsim_sitl.sh $$PX4_INSTANCE'
      echo ''
      echo 'Container waiting... (press Ctrl+C to stop)'
      # Keep container running
      tail -f /dev/null
    "

services:
  px4-bridge-drone-1:
    <<: *px4-common
    container_name: px4-bridge-drone-1
    hostname: px4-bridge-drone-1
    environment:
      <<: *px4-env
      PX4_INSTANCE: 1
    ports:
      - "4561:4561/tcp"  # Map PX4 MAVLink TCP port for drone 1
      - "14541:14541/udp"  # Control port local (UDP)
      - "14581:14581/udp"  # Control port remote (UDP)
    networks:
      px4_network:
        ipv4_address: 172.20.0.11

  px4-bridge-drone-2:
    <<: *px4-common
    container_name: px4-bridge-drone-2
    hostname: px4-bridge-drone-2
    environment:
      <<: *px4-env
      PX4_INSTANCE: 2
    ports:
      - "4562:4562/tcp"  # Map PX4 MAVLink TCP port for drone 2
      - "14542:14542/udp"  # Control port local (UDP)
      - "14582:14582/udp"  # Control port remote (UDP)
    networks:
      px4_network:
        ipv4_address: 172.20.0.12

  px4-bridge-drone-3:
    <<: *px4-common
    container_name: px4-bridge-drone-3
    hostname: px4-bridge-drone-3
    environment:
      <<: *px4-env
      PX4_INSTANCE: 3
    ports:
      - "4563:4563/tcp"  # Map PX4 MAVLink TCP port for drone 3
      - "14543:14543/udp"  # Control port local (UDP)
      - "14583:14583/udp"  # Control port remote (UDP)
    networks:
      px4_network:
        ipv4_address: 172.20.0.13

  px4-bridge-drone-4:
    <<: *px4-common
    container_name: px4-bridge-drone-4
    hostname: px4-bridge-drone-4
    environment:
      <<: *px4-env
      PX4_INSTANCE: 4
    ports:
      - "4564:4564/tcp"  # Map PX4 MAVLink TCP port for drone 4
      - "14544:14544/udp"  # Control port local (UDP)
      - "14584:14584/udp"  # Control port remote (UDP)
    networks:
      px4_network:
        ipv4_address: 172.20.0.14

  px4-bridge-drone-5:
    <<: *px4-common
    container_name: px4-bridge-drone-5
    hostname: px4-bridge-drone-5
    environment:
      <<: *px4-env
      PX4_INSTANCE: 5
    ports:
      - "4565:4565/tcp"  # Map PX4 MAVLink TCP port for drone 5
      - "14545:14545/udp"  # Control port local (UDP)
      - "14585:14585/udp"  # Control port remote (UDP)
    networks:
      px4_network:
        ipv4_address: 172.20.0.15

  px4-bridge-drone-6:
    <<: *px4-common
    container_name: px4-bridge-drone-6
    hostname: px4-bridge-drone-6
    environment:
      <<: *px4-env
      PX4_INSTANCE: 6
    ports:
      - "4566:4566"  # Map PX4 MAVLink port for drone 6
      - "14546:14546"  # Control port local
      - "14586:14586"  # Control port remote
    networks:
      px4_network:
        ipv4_address: 172.20.0.16

  px4-bridge-drone-7:
    <<: *px4-common
    container_name: px4-bridge-drone-7
    hostname: px4-bridge-drone-7
    environment:
      <<: *px4-env
      PX4_INSTANCE: 7
    ports:
      - "4567:4567"  # Map PX4 MAVLink port for drone 7
      - "14547:14547"  # Control port local
      - "14587:14587"  # Control port remote
    networks:
      px4_network:
        ipv4_address: 172.20.0.17

  px4-bridge-drone-8:
    <<: *px4-common
    container_name: px4-bridge-drone-8
    hostname: px4-bridge-drone-8
    environment:
      <<: *px4-env
      PX4_INSTANCE: 8
    ports:
      - "4568:4568"  # Map PX4 MAVLink port for drone 8
      - "14548:14548"  # Control port local
      - "14588:14588"  # Control port remote
    networks:
      px4_network:
        ipv4_address: 172.20.0.18

  px4-bridge-drone-9:
    <<: *px4-common
    container_name: px4-bridge-drone-9
    hostname: px4-bridge-drone-9
    environment:
      <<: *px4-env
      PX4_INSTANCE: 9
    ports:
      - "4569:4569"  # Map PX4 MAVLink port for drone 9
      - "14549:14549"  # Control port local
      - "14589:14589"  # Control port remote
    networks:
      px4_network:
        ipv4_address: 172.20.0.19

volumes:
  px4-shared-data:
    driver: local