version: '3.8'

services:
  px4-airsim-simple:
    build:
      context: .
      dockerfile: Dockerfile.simple
      args:
        - BUILDKIT_INLINE_CACHE=1
      network: host
    container_name: px4-airsim-simple-container
    ports:
      - "4560:4560"    # AirSim connection
      - "14550:14550"  # MAVLink GCS
    environment:
      - PX4_HOME_LAT=47.641468
      - PX4_HOME_LON=-122.140165
      - PX4_HOME_ALT=0.0
    volumes:
      - px4_simple_logs:/tmp/logs
      - px4_simple_data:/px4_ws/src/PX4-Autopilot/build
    networks:
      - px4-simple-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  px4_simple_logs:
  px4_simple_data:

networks:
  px4-simple-network:
    driver: bridge 